baseURL = 'https://blog.anandvivek.in/'
languageCode = 'en-us'
title = "Vivek's Blog"
theme = 'paper'

[params]
  color = 'linen'
  avatar = ''
  name = 'Vivek Anand'
  bio = 'Tech Lead · Backend Engineer · Open Source'

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'home'
    url = '/'
    weight = 1

[markup]
  [markup.highlight]
    style = 'dracula'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
